apiVersion: batch/v1
kind: Job
metadata:
  name: job
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: job
          image: python:latest
          command: [ "python3", "-c", "print('Hello from the Kubernetes job')" ]
      restartPolicy: Never
  ttlSecondsAfterFinished: 100
  backoffLimit: 4
